use_frameworks!
platform :ios, '10.0'

source 'git@github.com:zhang232425/ZJSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'ZJHome_Example' do
  
  pod 'ZJHome', :path => '../'
  
  pod 'ZJRoutableTargets',   :git => 'git@github.com:zhang232425/ZJRoutableTargets.git', :branch => 'main'
  pod 'ZJBase',              :git => 'git@github.com:zhang232425/ZJBase.git', :branch => 'main'
  pod 'ZJExtension',         :git => 'git@github.com:zhang232425/ZJExtension.git', :branch => 'main'

end
